# Generated by Django 5.0.4 on 2024-04-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=50)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
    ]
